#!/bin/bash
# Show a quick preview of the game screens

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║           🎮 BABY REVEAL PUZZLE GAME 🎮                      ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "This interactive game features:"
echo ""
echo "📝 PUZZLE 1: Word Scramble"
echo "   - Unscramble: YABB → BABY"
echo "   - Unscramble: UNNEJ → JUNE"
echo "   - Unscramble: ILFYMA → FAMILY"
echo ""
echo "🔢 PUZZLE 2: Math Riddles"
echo "   - How many months in half a year? → 6"
echo "   - What comes after 2025? → 2026"
echo "   - What is 3 + 6? → 9"
echo ""
echo "🔍 PUZZLE 3: Pattern Recognition"
echo "   - Jan, Feb, Mar, Apr, May, ___? → JUNE"
echo "   - 2023, 2024, 2025, ___? → 2026"
echo "   - Spring, Summer, Fall, Winter, ___? → SPRING"
echo ""
echo "❓ PUZZLE 4: Trivia Questions"
echo "   - What do you call a very young child? → Baby"
echo "   - When does summer begin? → June"
echo "   - What year comes after 2025? → 2026"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎊 FINAL REVEAL:"
echo ""
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║                                                           ║"
echo "║                  🍼  SPECIAL ANNOUNCEMENT  🍼             ║"
echo "║                                                           ║"
echo "║              A NEW BABY IS ON THE WAY! 👶                ║"
echo "║                                                           ║"
echo "║                  Expected Arrival:                        ║"
echo "║                  EARLY JUNE 2026                          ║"
echo "║                                                           ║"
echo "║            Get ready for a new adventure! 💕              ║"
echo "║                                                           ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "🎉 🎊 🎈 🎁 👶 💝 🌟 ✨ 💫 🎉 🎊 🎈"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "To play the full interactive game, run:"
echo "  python3 baby_reveal_game.py"
